import { RedirectButton } from "@/components/client/buttons";

import Menu from "@/constants/menu";

export const metadata = {
  title: "CodeCabinet",
  /**
   * @todo Update this description
   */
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <div className="h-screen w-56 flex-none">
        <ul className="menu space-y-3 bg-base-100">
          {Object.values(Menu).map(({ text, url }) => (
            <li key={url}>
              <RedirectButton
                className="active:selection btn-block btn"
                url={url}
              >
                {text}
              </RedirectButton>
            </li>
          ))}
        </ul>
      </div>
      <div className="p-10">{children}</div>
    </div>
  );
}
