import './globals.css'
import { Inter } from 'next/font/google'

import SessionProvider from "@/provider/SessionProvider";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <SessionProvider>
      <html lang="ja">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
